### ISSUE TITLE
referenced_object Template

### ISSUE THREAD

**Issue by realrespecter** [vmcall/owned_alignment#1]
Hellou vmcall!
Awesome project

On the line
`		this->driver_obj = referenced_object<DRIVER_OBJECT>();
`

You are using sort of **referenced_object** template. I tried to look on web, but could't find any reference.

**Comment by realrespecter** [comment]
I just rewroted everything that was missing

**Comment by Baitinq** [comment]
@realrespecter would you mind sharing it? thx
